### ISSUE TITLE
Expose LiteLLM supported params for LiteLLM Backend

### ISSUE THREAD

**Issue by hspak** [jackmpcollins/magentic#173]
[LiteLLM supports a bunch of params across different LLM providers](https://litellm.vercel.app/docs/completion/input#translated-openai-params) and it'd be nice to be able to pass these through magentic.

(If you have a suggested pattern for the implementation, I'd be happy to throw up a PR.)

**Comment by jackmpcollins** [comment]
Hey @hspak  A PR to add some of these would be great 👍  It would look similar to PR https://github.com/jackmpcollins/magentic/pull/71/files which added the `seed` param to the openai model. Based on that, the changes needed would be
- add the param to `LitellmChatModel` init method, add a property, and pass into the litellm completion call.
- add a setting corresponding to the new param in the settings class, and update the README and docs (new since PR)
- update or add a test to verify the changes are working

There are some params which won't make sense to add either because magentic uses them internally (e.g. `tools`, `stream=True`) or because the current syntax/API can't surface the result (e.g. `n` , `logprobs`). If you have a need for a param like those it would be great to understand more about your use case. Thanks

**Comment by hspak** [comment]
@jackmpcollins Hey thanks for the quick response and sorry for the delay. 

One use case that would be nice is the ability to propagate their [metadata](https://docs.litellm.ai/docs/completion/input#optional-fields) field in some way. LiteLLM offers a defining some custom callback handlers and we plan to have one for emitting some custom metrics. The `metadata` would be a nice way for us to attach some cardinality to our metrics.

I guess this is very LiteLLM backend specific, maybe it's something we can surface on `LitellmChatModel`?

**Comment by jackmpcollins** [comment]
@hspak  If the metadata is associated with the function (rather than the function invocation) then adding this as a param to `LitellmChatModel` would be the neatest, at least for the moment. You would then create functions like

```python
@prompt(
    "Create a Superhero named {name}.",
    model=LitellmChatModel("gpt-4", metadata={"foo": "bar"})
)
def create_superhero(name: str) -> Superhero: ...
```

---

If you instead want to set the metadata when the function is invoked it gets trickier. One option would be to support the `Placeholder` object in metadata ([docs](https://magentic.dev/chat-prompting/#placeholder)). So this would become

```python
@prompt(
    "Create a Superhero named {name}.",
    model=LitellmChatModel("gpt-4", metadata={"foo": Placeholder(str, "bar"})
)
def create_superhero(name: str, bar: str) -> Superhero: ...
```

When the function is called the placeholders would be replaced with the corresponding function arguments and the resulting metadata dictionary passed to the litellm completion function.

**Comment by hspak** [comment]
Amazing, thank you!
