### ISSUE TITLE
Proposal: Integrate Rubeus for LLM interoperability

### ISSUE THREAD

**Issue by Vrv18** [jackmpcollins/magentic#29]
Hi! I’m working on [Rubeus](https://github.com/portkey-AI/rubeus), a tool that could integrate with magnetic to enable easy swapping between different LLMs. It uses the same API signature as OpenAI, making integration straightforward. It also offers features like automatic fallbacks, retries, and load balancing. Would love to hear your thoughts!

**Comment by jackmpcollins** [comment]
That's pretty cool! Reminds me of https://route.withmartian.com/

For magentic to work with Rubeus right now you would need to support the OpenAI API including function calling. In future we could add a backend/ChatModel to magentic for the Rubeus API but I'd much rather do this if/when Rubeus supports function calling or structured responses of some kind. Otherwise there is a lot of prompt-engineering work that would have to go into magentic - this might happen anyway to support models other than openai chat models, but hopefully this can be achieved via packages that will handle enforcing structure like https://github.com/outlines-dev/outlines or https://github.com/guidance-ai/guidance

**Comment by Vrv18** [comment]
@jackmpcollins thank you! Rubeus does support OpenAI functions. You can pass both `functions` and `function_call` just as you would in an OpenAI call in params, and you're set.

**Comment by jackmpcollins** [comment]
Closing this as Rubeus/Gateway matches the OpenAI API so should work with magentic by setting the `MAGENTIC_OPENAI_BASE_URL` env var. For more info see https://magentic.dev/configuration/
