### ISSUE TITLE
Is it possible to make one of the several offered functions in a ParallelFunctionCall required?

### ISSUE THREAD

**Issue by CiANSfi** [jackmpcollins/magentic#296]
Copying this simple example from the documentation to illustrate:

`@prompt(
    "Use the appropriate search functions to answer: {question}",
    functions=[search_twitter, search_youtube],
)
def perform_search(question: str) -> ParallelFunctionCall[str]: ...`

Is there a way to say make `search_twitter` a mandatory function that must be called each time?

**Comment by jackmpcollins** [comment]
@CiANSfi  I don't think the OpenAI or Anthropic APIs support this, but if you can find a way to do it with them directly then we can figure out a way to do this via magentic too.

If you always want _only_ the `search_twitter` function to be called then you can just provide it as the only function in `functions` and type the response as `-> FunctionCall[str]`. Otherwise you could try updating your prompt to encourage the model to always call this function (of course that's not guaranteed to work).

**Comment by CiANSfi** [comment]
Yeah, I think maybe I should just use a @prompt_chain, so instead of hypothetically marking a function as "required", it'll just have to be called no matter what as part of a stepwise process. Or really just de-couple it and have the required function be called explicitly no matter what and then I'll move on to the rest afterwarsd.

**Comment by CiANSfi** [comment]
Yeah, I think maybe I should just use a @prompt_chain, so instead of hypothetically marking a function as "required", it'll just have to be called no matter what as part of a stepwise process. Or really just de-couple it and have the required function be called explicitly no matter what and then I'll move on to the rest afterwards.
