### ISSUE TITLE
Proposal: Custom base url/parameters environment variables for AI gateways

### ISSUE THREAD

**Issue by peteallport** [jackmpcollins/magentic#38]
Would be neat to support environment variables for base url and necessary key/value parameters to support AI gateways, like Cloudflare's offering!

> ### AI Gateway
> [Cloudflare AI Gateway Documentation](https://developers.cloudflare.com/ai-gateway/)
> Cloudflare’s AI Gateway allows you to gain visibility and control over your AI apps. By connecting your apps to AI Gateway, you can gather insights on how people are using your application with analytics and logging and then control how your application scales with features such as caching, rate limiting, as well as request retries, model fallback, and more. Better yet - it only takes one line of code to get started.

**Comment by jackmpcollins** [comment]
Hi @peteallport  Since magentic uses the `openai` python package, setting the `OPENAI_API_BASE` environment variable or `openai.api_base` will work. This would allow you to use [the OpenAI cloudflare url](https://developers.cloudflare.com/ai-gateway/get-started/connecting-applications/#openai).

For the HuggingFace and Replicate endpoints I will need to add an additional backend (probably using [LiteLLM](https://github.com/BerriAI/litellm), see PR https://github.com/jackmpcollins/magentic/pull/37) and also decide on how to support models that do not have function calling / structured output.

For the universal endpoint either you could ask LiteLLM to add support for this, or I could add another backend specifically for this. Do you know if there is a python client package for Cloudflare AI Gateway?

**Comment by ishaan-jaff** [comment]
Hi I'm the maintainer of LiteLLM @peteallport - I believe we support the universal gateway through this: https://docs.litellm.ai/docs/providers/custom_openai_proxy

**Comment by jackmpcollins** [comment]
Closing this as it should be possible to use most LLMs through openai-compatible APIs or using the LiteLLM backend. For more info see https://magentic.dev/configuration/
