### ISSUE TITLE
Update prompt to return NULL, but GPT model won't return NULL.

### ISSUE THREAD

**Issue by tahirs95** [jackmpcollins/magentic#61]
I have defined an **ENUM** class like:

class **SamsungPhoneModel**(Enum):
    """Represents distinct Samsung Phone models"""
    GALAXY_CORE_PLUS_350 = "GALAXY CORE PLUS 350"
    GALAXY_FAME_LITE = "GALAXY FAME LITE"
    GALAXY_S4 = "GALAXY S4"
    UNDEFINED = ""

My prompt is: Classify the product title: {product_title} into a one of the specific model types as defined by SamsungPhoneModel.

If the product title is **Galaxy S7 Active**, which isn't present in Enum class. I would assume that Magentic should return "UNDEFINED" but it throws error that:

**Failed to parse model output. You may need to update your prompt to encourage the model to return a specific type.**

**Comment by jackmpcollins** [comment]
@tahirs95  I was able to recreate the error with the following code.

```python
from enum import Enum

from magentic import prompt


class SamsungPhoneModel(Enum):
    """Represents distinct Samsung Phone models"""
    GALAXY_CORE_PLUS_350 = "GALAXY CORE PLUS 350"
    GALAXY_FAME_LITE = "GALAXY FAME LITE"
    GALAXY_S4 = "GALAXY S4"
    UNDEFINED = ""


@prompt(
    "Classify the product title: {product_title} into a one of the specific model types as defined by SamsungPhoneModel."
)
def classify_phone_model(product_title: str) -> SamsungPhoneModel:
    ...


classify_phone_model("Galaxy S7 Active")
```

```
ValidationError: 1 validation error for Output[SamsungPhoneModel]
value
  Input should be 'GALAXY CORE PLUS 350','GALAXY FAME LITE','GALAXY S4' or '' [type=enum, input_value='Galaxy S7 Active', input_type=str]
```

The error indicates that the model is returning the value `'Galaxy S7 Active'` which is not part of the enum. You _could_ update the prompt to try prevent this but this won't be a robust solution, for example by adding "If the product does not match an allowed model type return an empty string.". But in this case the best option is probably to use [the `_missing_` method of Enum](https://docs.python.org/3/library/enum.html#enum.Enum._missing_) which allows you to set a value for unknown inputs. So when the model output is not one of the specific values you will get the undefined value rather than an error.


```python
class SamsungPhoneModel(Enum):
    """Represents distinct Samsung Phone models"""
    GALAXY_CORE_PLUS_350 = "GALAXY CORE PLUS 350"
    GALAXY_FAME_LITE = "GALAXY FAME LITE"
    GALAXY_S4 = "GALAXY S4"
    UNDEFINED = ""

    @classmethod
    def _missing_(cls, value):
        return cls.UNDEFINED
```

Please reopen this issue if this does not solve your problem. Thanks for using the package!

**Comment by tahirs95** [comment]
Thanks for the details.

One more thing is that:

class **SamsungPhoneModel**(Enum):
    """Represents distinct Samsung Phone models"""
    SAMSUNG_GALAXY_NOTE_9 = "SAMSUNG GALAXY NOTE 9"

classify_phone_model("Galaxy Note 9 Pro")

It returns: **SAMSUNG_GALAXY_NOTE_9**

If I ask GPT4 to extract model number without using Magentic, it returns **Galaxy Note 9 Pro**, which is **UNDEFINED** since its not in the ENUM class, but magentic is returning **NOTE 9**, that's incorrect. 

Magentic works fine when I add to the class:
SAMSUNG_GALAXY_NOTE_9_PRO = "SAMSUNG GALAXY NOTE 9 PRO"
****
