### ISSUE TITLE
Support for reproducible outputs

### ISSUE THREAD

**Issue by Lawouach** [jackmpcollins/magentic#68]
Hello,

Terrific library, thank you for this!

I was hoping to be able to pass extra OpenAI parameters as I wanted to experiment with new [reproducible output feature](https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed). But it seems we can't really interact with the underlying OpenAI instance. Is that something you'd consider propagating down at some point?

**Comment by jackmpcollins** [comment]
Thanks @Lawouach  Added this as a parameter and released now in https://github.com/jackmpcollins/magentic/releases/tag/v0.12.0

In general I prefer to add each of the needed parameters to magentic rather than allowing passing arbitrary arguments to openai because there are some params that magentic uses (functions, stream) and some that don't make sense in this context (n).

**Comment by Lawouach** [comment]
Thanks a lot @jackmpcollins
